### PR TITLE
Move buildbot images to 2022.

### PR DESCRIPTION
**Pull request by foopoiuyt**
Update the images to be based on msbuild-2022 and update the startup script
for the change.

### CODE REVIEW

**Review by donny-dont — APPROVED** [review]
:shipit: 

If you want to shuffle things around so msbuild is based on 2022 that's fine too or we can just make all the msbuild images numbered.

**Comment by donny-dont** [comment]
Build failed cause the script is building `msbuild` not `msbuild-2022` @foopoiuyt

**Comment by foopoiuyt** [comment]
I was figuring we'd eventually change msbuild to msbuild-2019, but figured that could be separate.

**Comment by donny-dont** [comment]
Yea maybe we should just keep it numbered so there isn't any churn.

Anyways will squash and merge once the build comes back.

**Pull request merged**
