### PR TITLE
Remove msbuild-2017 from build and publish

### PR DESCRIPTION
**Pull request by donny-dont**
The msbuild-2017 image is no longer needed so remove it from the scripts.

### CODE REVIEW

**Comment by foopoiuyt** [comment]
Is there a reason to leave the actual msbuild-2017 directories?

**Comment by donny-dont** [comment]
We left ews-legacy around but I'm fine with just deleting them all if you prefer.

**Comment by foopoiuyt** [comment]
I didn't actually notice we hadn't removed the ews-legacy images. I think it's probably worth cleaning them out at some point.

**Comment by donny-dont** [comment]
Ask and ye shall receive https://github.com/WebKitForWindows/docker-webkit-dev/pull/275 gets rid of ews-legacy and the images are deleted here as well.

**Review by foopoiuyt — APPROVED** [review]
This is fine, but would have to land after #274 presumably since the removal of from .drone.jsonnet isn't in this one.

**Pull request merged**
